# src/ingestion/ait_ads.py
"""
Loader for the AIT Alert Data Set (AIT-ADS) -- real Wazuh/Suricata/AMiner
alerts generated by running actual IDS tools against the AIT Log Data Set
V2 (AIT-LDSv2), the same log-dataset lineage (Landauer/Skopik/Wurzenberger,
AIT Austrian Institute of Technology) AgCyRAG's own paper cites (ref [27])
as its data source. Zenodo record: 10.5281/zenodo.8263181 (CC-BY-4.0).

This data has genuine multi-alert correlation structure: a handful of hosts
hit repeatedly (thousands of alerts each), not one alert per host -- so
Cypher/vector retrieval actually has history to correlate against. It also
carries real Wazuh MITRE tagging (rule.mitre.id/technique/tactic) natively
on ~36% of alerts, no invented mapping needed.

No per-alert "should escalate" label exists. Ground truth instead is
attack-phase TIME WINDOWS (data/labels.csv-style: scenario, phase,
start_unix, end_unix) -- an alert's phase (or "background noise" if it
falls outside every window) is derived by checking whether its timestamp
falls inside one of the scenario's labeled windows. This is the same
derivation the dataset's own paper describes for producing time_label.

Files (not checked into git -- large, download separately):
    Zenodo record 8263181: ait_ads.zip (per-scenario {scenario}_wazuh.json /
    {scenario}_aminer.json, JSON-lines) + labels.csv (phase windows).
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from src.ingestion.schema import Alert

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"


@dataclass
class PhaseWindow:
    phase: str
    start: float
    end: float


def load_phase_windows(labels_csv: Path, scenario: str) -> List[PhaseWindow]:
    import csv

    windows = []
    with open(labels_csv) as f:
        for row in csv.DictReader(f):
            if row["scenario"] == scenario:
                windows.append(PhaseWindow(row["attack"], float(row["start"]), float(row["end"])))
    return windows


def classify_phase(ts: float, windows: List[PhaseWindow]) -> Optional[str]:
    for w in windows:
        if w.start <= ts <= w.end:
            return w.phase
    return None


def _parse_iso_ts(ts_str: str) -> float:
    return datetime.fromisoformat(ts_str.replace("Z", "+00:00")).timestamp()


def alert_id(scenario: str, raw: dict, idx: int) -> str:
    rule_id = raw.get("rule", {}).get("id", "0")
    return f"ait-{scenario}-{rule_id}-{idx}"


def to_alert(raw: dict, scenario: str, idx: int) -> Optional[Alert]:
    """predecoder.hostname is the actual monitored host for syslog-sourced
    alerts (agent.name is uniformly "wazuh-client", the collector's own
    identity, never useful as a host entity). Network-layer alerts (Suricata/
    snort-decoded: dirb/wpscan/webshell scans, and -- critically -- almost
    all level>=7 alerts across every AIT-ADS scenario, confirmed by a direct
    scan of the raw per-scenario files) have no predecoder.hostname. The
    original fallback here (data.dest_ip) barely helped: these alerts use
    data.dstip (no underscore, different key), and even where dest_ip does
    exist it's typically an *external* target the host was talking to (e.g.
    a package-update server), not one of the monitored hosts. agent.ip is
    the actual internal host that generated the alert -- verified present on
    778/778 (100%) of the level>=7 alerts that predecoder.hostname/dest_ip
    alone left unrepresentable in the russellmitchell scenario. Without this
    fallback, the whole high-severity tail of AIT-ADS (dirb/wpscan/webshell,
    and most of what would ever cross TRIGGER_SEVERITY_THRESHOLD) is
    unrepresentable no matter the sample size or scenario chosen."""
    rule = raw.get("rule", {})
    mitre = rule.get("mitre", {})
    data = raw.get("data", {})
    src_ip = data.get("src_ip") or data.get("srcip")

    hostname = (
        raw.get("predecoder", {}).get("hostname")
        or raw.get("agent", {}).get("ip")
        or data.get("dest_ip")
        or data.get("dstip")
    )
    if not hostname:
        return None

    ts_str = raw.get("@timestamp")
    if not ts_str:
        return None

    return Alert(
        id=alert_id(scenario, raw, idx),
        timestamp=ts_str,
        agent_name=hostname,
        rule_id=int(rule.get("id", 0)),
        rule_level=int(rule.get("level", 0)),
        rule_description=rule.get("description", ""),
        rule_groups=rule.get("groups", []),
        rule_mitre_id=mitre.get("id", []),
        rule_mitre_tactic=mitre.get("tactic", []),
        data_srcip=src_ip,
        decoder_name=raw.get("decoder", {}).get("name"),
        full_log=raw.get("full_log", ""),
        scenario_id=f"real-ait-{scenario}",
    )


def to_ground_truth(raw: dict, scenario: str, idx: int, phase: Optional[str]) -> dict:
    mitre = raw.get("rule", {}).get("mitre", {})
    mitre_ids = mitre.get("id", [])
    return {
        "alert_id": alert_id(scenario, raw, idx),
        "scenario": scenario,
        "phase": phase,  # attack phase name, or None = background noise
        "should_escalate": phase is not None,
        "mitre_technique": mitre_ids[0] if mitre_ids else None,
        "mitre_tactic": (mitre.get("tactic") or [None])[0],
        "has_native_mitre_tag": bool(mitre_ids),
    }


def load_scenario_sample(
    scenario: str,
    wazuh_json_path: Path,
    labels_csv: Path,
    max_per_phase: int = 20,
    n_noise: int = 40,
    seed: int = 42,
) -> List[dict]:
    """Returns [{"alert": Alert, "ground_truth": {...}}, ...]: up to
    `max_per_phase` alerts per labeled attack phase (some phases have far
    fewer than that available -- takes all of them), plus `n_noise` alerts
    randomly sampled from outside every labeled window, so the sample keeps
    phase diversity instead of being swamped by whichever phase happens to
    fire the most alerts (dirb/wpscan fire thousands; webshell/
    privilege_escalation fire only a handful)."""
    import random

    windows = load_phase_windows(labels_csv, scenario)
    rng = random.Random(seed)

    by_phase: Dict[str, List[Tuple[dict, int]]] = {}
    noise_pool: List[Tuple[dict, int]] = []

    with open(wazuh_json_path) as f:
        for idx, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            raw = json.loads(line)
            ts_str = raw.get("@timestamp")
            if not ts_str:
                continue
            ts = _parse_iso_ts(ts_str)
            phase = classify_phase(ts, windows)
            if phase:
                by_phase.setdefault(phase, []).append((raw, idx))
            else:
                noise_pool.append((raw, idx))

    selected: List[Tuple[dict, int, Optional[str]]] = []
    for phase, items in by_phase.items():
        chosen = items if len(items) <= max_per_phase else rng.sample(items, max_per_phase)
        selected.extend((raw, idx, phase) for raw, idx in chosen)

    noise_chosen = noise_pool if len(noise_pool) <= n_noise else rng.sample(noise_pool, n_noise)
    selected.extend((raw, idx, None) for raw, idx in noise_chosen)

    records = []
    for raw, idx, phase in selected:
        alert = to_alert(raw, scenario, idx)
        if alert is None:
            continue
        records.append({"alert": alert, "ground_truth": to_ground_truth(raw, scenario, idx, phase)})

    records.sort(key=lambda r: r["alert"].timestamp)
    return records


def write_ait_ads_alerts(
    scenario: str = "russellmitchell",
    wazuh_json_path: Optional[Path] = None,
    labels_csv: Optional[Path] = None,
    max_per_phase: int = 20,
    n_noise: int = 40,
    seed: int = 42,
    alerts_path: Optional[Path] = None,
    ground_truth_path: Optional[Path] = None,
) -> Tuple[Path, Path, List[dict]]:
    if wazuh_json_path is None or labels_csv is None:
        raise ValueError(
            "wazuh_json_path and labels_csv must be given explicitly -- the "
            "AIT-ADS zip/JSON files aren't checked into the repo (large). "
            "Download from https://zenodo.org/records/8263181 first."
        )
    alerts_path = alerts_path or (DATA_DIR / "alerts.jsonl")
    ground_truth_path = ground_truth_path or (DATA_DIR / "alerts_ground_truth.json")
    DATA_DIR.mkdir(exist_ok=True)

    records = load_scenario_sample(
        scenario, wazuh_json_path, labels_csv, max_per_phase=max_per_phase, n_noise=n_noise, seed=seed
    )

    with open(alerts_path, "w") as f:
        for r in records:
            f.write(json.dumps(r["alert"].to_jsonl_record()) + "\n")

    ground_truth = {r["ground_truth"]["alert_id"]: r["ground_truth"] for r in records}
    with open(ground_truth_path, "w") as f:
        json.dump(ground_truth, f, indent=2)

    return alerts_path, ground_truth_path, records


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Load an AIT-ADS scenario sample as the main alert data.")
    parser.add_argument("--scenario", default="russellmitchell")
    parser.add_argument("--wazuh-json", required=True, help="Path to {scenario}_wazuh.json")
    parser.add_argument("--labels-csv", required=True, help="Path to labels.csv")
    parser.add_argument("--max-per-phase", type=int, default=20)
    parser.add_argument("--n-noise", type=int, default=40)
    args = parser.parse_args()

    alerts_path, gt_path, records = write_ait_ads_alerts(
        scenario=args.scenario,
        wazuh_json_path=Path(args.wazuh_json),
        labels_csv=Path(args.labels_csv),
        max_per_phase=args.max_per_phase,
        n_noise=args.n_noise,
    )
    n_signal = sum(1 for r in records if r["ground_truth"]["should_escalate"])
    n_mitre = sum(1 for r in records if r["ground_truth"]["has_native_mitre_tag"])
    print(f"Wrote {len(records)} alerts to {alerts_path} ({n_signal} in a labeled attack phase, {n_mitre} with a native MITRE tag)")
    print(f"Ground truth sidecar written to {gt_path}")
